// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/decohub.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$$$$0 from "./sections/Footer.tsx";
import * as $$$$$$1 from "./sections/Header.tsx";
import * as $$$$$$2 from "./sections/Hero.tsx";
import * as $$$$$$3 from "./sections/ItWorks.tsx";
import * as $$$$$$7 from "./sections/myHero.tsx";
import * as $$$$$$4 from "./sections/ParagraphList.tsx";
import * as $$$$$$8 from "./sections/sections/ItWorks.tsx";
import * as $$$$$$5 from "./sections/SimpleTextList.tsx";
import * as $$$$$$6 from "./sections/Theme/Theme.tsx";

const manifest = {
  "sections": {
    "deco-sites/honda-jdm/sections/Footer.tsx": $$$$$$0,
    "deco-sites/honda-jdm/sections/Header.tsx": $$$$$$1,
    "deco-sites/honda-jdm/sections/Hero.tsx": $$$$$$2,
    "deco-sites/honda-jdm/sections/ItWorks.tsx": $$$$$$3,
    "deco-sites/honda-jdm/sections/myHero.tsx": $$$$$$7,
    "deco-sites/honda-jdm/sections/ParagraphList.tsx": $$$$$$4,
    "deco-sites/honda-jdm/sections/sections/ItWorks.tsx": $$$$$$8,
    "deco-sites/honda-jdm/sections/SimpleTextList.tsx": $$$$$$5,
    "deco-sites/honda-jdm/sections/Theme/Theme.tsx": $$$$$$6,
  },
  "apps": {
    "deco-sites/honda-jdm/apps/decohub.ts": $$$$$$$$$$$0,
    "deco-sites/honda-jdm/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "deco-sites/honda-jdm",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
